[phases.setup]
nixPkgs = [ 'nodejs@20' ]

[phases.install]
cmds = [
   'corepack enable',
   'pnpm install'
]

[phases.build]
cmds = [
   'pnpm build:registry',
   'pnpm --filter=web build'
]

[variables]
NIXPACKS_TURBO_APP_NAME = "web"
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://nyxbui.design"

[start]
cmd = 'pnpm --filter=web start'
